name: Build ViTune APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip -P /tmp
          unzip -d /opt/gradle /tmp/gradle-7.6-bin.zip
          echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> $GITHUB_ENV

      - name: Check directory structure
        run: |
          ls -la
          ls -la ViTune/ViTune

      - name: Build APK using Gradle
        run: gradle assembleDebug
        working-directory: ViTune/ViTune

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vitune-apk
          path: ViTune/ViTune/app/build/outputs/apk/debug/app-debug.apk
